---
- name: Keystone service provider
  hosts: sp
  user: centos
  become: true
  become_method: sudo
  gather_facts: true

  roles:
  - hosts
  - sp

- name: Keystone identity provider
  hosts: idp
  user: centos
  become: true
  become_method: sudo
  gather_facts: true

  roles:
  - hosts
