version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keystone
      MYSQL_USER: keystone
      MYSQL_PASSWORD: keystone
    volumes:
    - ./data/mysql_data:/var/lib/mysql
    networks:
      idp:
        ipv4_address: 172.100.100.10
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: keystone
      RABBITMQ_DEFAULT_PASS: keystone
      RABBITMQ_DEFAULT_VHOST: openstack
    volumes:
    - ./data/rabbitmq_data:/var/lib/rabbitmq
    networks:
      idp:
        ipv4_address: 172.100.100.11
  keystone-uwsgi:
    build:
      context: ./keystone
    image: keystone
    environment:
      TRANSPORT_URL: "rabbit://keystone:keystone@rabbitmq:5672/openstack/"
      CONNECTION: "mysql+pymysql://keystone:keystone@mysql:3306/keystone"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      idp:
        ipv4_address: 172.100.100.12
  keystone:
    build:
      context: ./keystone-proxy
    image: keystone-proxy
    ports:
    - "80:80"
    environment:
      KEYSTONE_UWSGI_HOST: keystone-uwsgi
      SERVER_NAME: keystone
    depends_on:
      - keystone-uwsgi
    networks:
      idp:
        ipv4_address: 172.100.100.100

networks:
  idp:
    ipam:
      driver: default
      config:
      - subnet: "172.100.100.0/24"
